@startuml

title "Arquitectura Nestjs"

class Controller <<controller>>
class Service <<controller>>
class Model
class Dto

Controller --> Service
Service --> Model
Service --> Dto
Controller ..> Dto

@enduml