@startuml
title "Diagramna de secuencia de Arquitectura NestJs"

actor User
control "Controller" as Controller
control "Service" as Service
database Repository
entity Model

User -> Controller : GET request
Controller -> Service : getAll
Service -> Repository : getAll
Repository -> Model : get
Repository -> Service : response Model
Service -> Service : createDto(Model)
Service -> Controller: response Dto
User <-- Controller : response (Dto)

@enduml