@startuml

title "Arquitectura Angular Componente"

component ViewComponent <<MVP-VM>> {
    class Component <<presenter>>
    class Css <<¿model?>>
    class HtmlTemplate <<view>>
    
    Component -right-> Css
    Component <-down-> HtmlTemplate : Data Binding

    note top of Component 
        Metadata:
            -template: enlace / integrado
            -css: enlace / integrado
    end note

    
}

class Service <<model>>
Component -right-> Service

@enduml