@startuml

title "Arquitectura Angular"

component Main
component NgModule <<Package>> 
component C as "Component" <<View>>
component Injector {
    component Service <<Controllers>>
}
component Model <<Model>> 

NgModule --> "0..*" NgModule
Main --> NgModule
NgModule *--> "1..*" C
Injector .up.> C : Inject service
C -down-> Service
Service ..> Model
C ..> Model

@enduml